env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
overrides:
  - files: ["*.js", "*.mjs"]
