site_name: tracing-node
repo_url: https://github.com/saidsef/tracing-node
strict: true
theme:
  name: material
  palette:
    primary: teal
  features:
  - content.code.copy
  - content.tabs.link
markdown_extensions:
- codehilite
- admonition
- tables
- toc:
    permalink: true
    toc_depth: 3
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Usage:
    - Configuration: usage.md
    - Instrumentation: instrumentation.md
  - Deployment: deployment.md
  - Testing: testing.md
  - Troubleshooting: troubleshooting.md
