apiVersion: v1
kind: Pod
metadata:
  name: tracing-node
  labels:
    app.kubernetes.io/name: tracing-node
spec:
  activeDeadlineSeconds: 120
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Never
  preemptionPolicy: PreemptLowerPriority
  containers:
  - name: tracing-node
    image: docker.io/node:20-alpine3.19
    workingDir: "/app"
    command:
      - /bin/sh
    args:
      - -c
      - "npm install && node libs/index.js"
    resources:
      limits:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
      - name: git
        mountPath: /app
  volumes:
    - name: git
      gitRepo:
        directory: "."
        repository: "https://github.com/saidsef/tracing-node.git"
        revision: "dependabot-npm_and_yarn-opentelemetry-instrumentation-aws-sdk-0.37.2"
