apiVersion: v1
kind: Pod
metadata:
  name: tracing-node
  labels:
    app.kubernetes.io/name: tracing-node
spec:
  activeDeadlineSeconds: 120
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Never
  preemptionPolicy: PreemptLowerPriority
  containers:
  - name: tracing-node
    image: docker.io/node:20-alpine3.19
    args:
      - node
      - libs/index.js
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      capabilities:
        drop:
          - ALL
