apiVersion: v1
kind: Pod
metadata:
  name: tracing-node
  labels:
    app.kubernetes.io/name: tracing-node
spec:
  activeDeadlineSeconds: 240
  automountServiceAccountToken: false
  enableServiceLinks: false
  restartPolicy: Never
  preemptionPolicy: PreemptLowerPriority
  containers:
  - name: tracing-node
    image: docker.io/node:20-alpine3.19
    workingDir: "/app"
    command:
      - /bin/sh
    args:
      - -c
      - "npm install && node libs/index.mjs && npm run test"
    resources:
      limits:
        memory: "1Gi"
        cpu: "80m"
      requests:
        memory: "1Gi"
        cpu: "50m"
    volumeMounts:
      - name: git
        mountPath: /app
  volumes:
    - name: git
      gitRepo:
        directory: "."
        repository: "https://github.com/saidsef/tracing-node.git"
        revision: "tracing-shutdown"
